# Markdown options
markdown: kramdown
highlighter: rouge
kramdown:
    auto_ids: true # make ids for each header
    input: GFM

redcarpet:
  extensions:
    - "autolink"

# jekyll plugins
gems:
  - jekyll-feed
  - jekyll-gist
